### ISSUE TITLE
Library path

### ISSUE THREAD

**Issue by Geetima2021** [ankurxyz/VSD_TCL#1]
I executed your code and the approach you have taken of using the relative path is really however please check your library path as i got an error while executing it.

![error_ankur](https://github.com/ankurxyz/VSD_TCL/assets/63381455/71ef022a-bcab-4975-98d5-3540d0edf2cd)

**Comment by ankurxyz** [comment]
Hi Geetima,

I had deliberately put files in different path for uploading into the
github repo.

Please check now.

I have restored files to their original path on github repo.

Kindly let me know if the issue persists.

Thanks and Regards,
Ankur

**Comment by ankurxyz** [comment]
Issue resolved.
